# Generated by Django 4.2.14 on 2024-07-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'collected'), (3, 'delivered'), (4, 'partially_collected')], default=1, max_length=20),
        ),
    ]
