# Generated by Django 4.2.14 on 2024-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_amount_collected_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'collected'), (3, 'delivered'), (4, 'partially_collected')], db_index=True, default=1, max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'amount_due_at'], name='task_task_status_be37ab_idx'),
        ),
    ]
