# Generated by Django 4.2.14 on 2024-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
