# Generated by Django 4.2.14 on 2024-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_frozen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_frozen',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
