# Generated by Django 4.2.14 on 2024-07-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_cashcollector_manager_user_first_name_user_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='last modified datetime')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('collect', 'Collect'), ('deliver', 'Deliver')], max_length=10)),
                ('cash_collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.cashcollector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
