# Generated by Django 4.2.14 on 2024-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'collect'), (2, 'deliver')], default=1),
        ),
    ]
